### Get Movies
GET http://localhost:8080/movies

### Get a movie by id
GET http://localhost:8080/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Get a movie by genre
GET http://localhost:8080/movies?genre=Sci-Fi